version: "3"

networks:
  aero:

services:
  site:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: aero_nginx
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html:delegated
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - redis
      - mysql
      - mailhog
      - elasticsearch
    networks:
      - aero

  mysql:
    image: mysql:5.7.29
    container_name: aero_mysql
    restart: unless-stopped
    tty: true
    ports:
      - 3336:3306
    environment:
      MYSQL_DATABASE: aero
      MYSQL_USER: aero
      MYSQL_PASSWORD: aero
      MYSQL_ROOT_PASSWORD: aero
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - aero
    volumes:
      - ./mysql:/var/lib/mysql

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: aero_php
    volumes:
      - ./src:/var/www/html:delegated
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - aero

  redis:
    image: redis:alpine
    container_name: aero_redis
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - aero

  mailhog:
    image: mailhog/mailhog:latest
    container_name: aero_mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - aero

  elasticsearch:
    image: elasticsearch:6.8.15
    container_name: aero_elasticsearch
    restart: unless-stopped
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node
    networks:
      - aero

volumes:
  esdata:
    driver: local